
package proyecto.programacion02.views;

import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import proyecto.programacion02.controllers.CategoriaDAO;
import proyecto.programacion02.controllers.Conexion;
import proyecto.programacion02.controllers.ProductoDAO;
import proyecto.programacion02.controllers.ProveedorDAO;
import proyecto.programacion02.models.Categoria;
import proyecto.programacion02.models.Producto;
import proyecto.programacion02.models.Proveedor;

/**
 *
 * @author reymo 
 */
public class frmProducto extends javax.swing.JInternalFrame {
     ProductoDAO productosDao = new ProductoDAO();
    CategoriaDAO categoriaDao;
    ProveedorDAO proveedoresDao;
    /**
     * Creates new form frmProducto1
     */
    
    
    public frmProducto() {
        initComponents();
        //Esto carga la informacion en los combobox 
        this.cmbProveedor.setModel(productosDao.Obt_Proveedor());
        this.cmbCategoria.setModel(productosDao.Obt_Categoria());
        cargarDatosProducto();
         categoriaDao = new CategoriaDAO();
         proveedoresDao = new ProveedorDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winProducto = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtUnidades = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        cmbProveedor = new javax.swing.JComboBox<>();
        btnAddProveedor = new javax.swing.JButton();
        btnAddCatego = new javax.swing.JButton();
        winAddCategoria = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCategoriaId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNombreDesc = new javax.swing.JTextArea();
        btnAtrasCategoria = new javax.swing.JButton();
        btnSaveCategoria = new javax.swing.JButton();
        winAddProveedor = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdWinProveedor = new javax.swing.JTextField();
        txtCompaniaWinProveedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRepresentanteWinProveedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTelefonoWinProveedor = new javax.swing.JTextField();
        btnGuardarProveedor = new javax.swing.JButton();
        btnCerrarProveedor = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnEnviarDatos = new javax.swing.JMenuItem();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtDatos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cmbSelect = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/product.png"))); // NOI18N
        jLabel1.setText("Registro de Producto");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/id.png"))); // NOI18N
        jLabel2.setText("Codigo Producto");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/blog.png"))); // NOI18N
        jLabel3.setText("Nombre Producto");
        jLabel3.setAutoscrolls(true);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N
        jLabel4.setText("Precio Unidad");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/quantity.png"))); // NOI18N
        jLabel5.setText("Unidades en existencia");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fast-delivery.png"))); // NOI18N
        jLabel6.setText("Codigo Proveedor");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/post.png"))); // NOI18N
        jLabel7.setText("Codigo Categoria");

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/success.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cleaning.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnAceptar)
                .addGap(30, 30, 30)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnCancelar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        cmbProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProveedorActionPerformed(evt);
            }
        });

        btnAddProveedor.setText("Agregar Proveedor");
        btnAddProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProveedorActionPerformed(evt);
            }
        });

        btnAddCatego.setText("Agregar Categoria");
        btnAddCatego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winProductoLayout = new javax.swing.GroupLayout(winProducto.getContentPane());
        winProducto.getContentPane().setLayout(winProductoLayout);
        winProductoLayout.setHorizontalGroup(
            winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winProductoLayout.createSequentialGroup()
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winProductoLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(winProductoLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(winProductoLayout.createSequentialGroup()
                                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)))
                                .addGap(26, 26, 26)
                                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUnidades, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                        .addComponent(txtProducto)
                                        .addComponent(cmbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnAddCatego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        winProductoLayout.setVerticalGroup(
            winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winProductoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnAddProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(winProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddCatego, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seo-and-web.png"))); // NOI18N
        jLabel11.setText("Registro Categoria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aaaid card.png"))); // NOI18N
        jLabel8.setText("ID Categoria:");

        txtCategoriaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaIdActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/taggg.png"))); // NOI18N
        jLabel9.setText("<html>Nombre Categoria:<html>");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descripcion.png"))); // NOI18N
        jLabel10.setText("Descripción:");

        txtNombreDesc.setColumns(20);
        txtNombreDesc.setRows(5);
        jScrollPane2.setViewportView(txtNombreDesc);

        btnAtrasCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnAtrasCategoria.setText("Cerrar");
        btnAtrasCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCategoriaActionPerformed(evt);
            }
        });

        btnSaveCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/success.png"))); // NOI18N
        btnSaveCategoria.setText("Guardar");
        btnSaveCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategoriaId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSaveCategoria)
                .addGap(18, 18, 18)
                .addComponent(btnAtrasCategoria)
                .addGap(79, 79, 79))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCategoriaId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasCategoria)
                    .addComponent(btnSaveCategoria))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout winAddCategoriaLayout = new javax.swing.GroupLayout(winAddCategoria.getContentPane());
        winAddCategoria.getContentPane().setLayout(winAddCategoriaLayout);
        winAddCategoriaLayout.setHorizontalGroup(
            winAddCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winAddCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        winAddCategoriaLayout.setVerticalGroup(
            winAddCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winAddCategoriaLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delivery-truck.png"))); // NOI18N
        jLabel12.setText("Registro de Proveedores");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel12)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aaaid card.png"))); // NOI18N
        jLabel13.setText("Cedula:");

        txtIdWinProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdWinProveedorActionPerformed(evt);
            }
        });

        txtCompaniaWinProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompaniaWinProveedorActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/company.png"))); // NOI18N
        jLabel14.setText("Compañia:");

        txtRepresentanteWinProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepresentanteWinProveedorActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/partnership-handshake.png"))); // NOI18N
        jLabel15.setText("Representnte:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phone.png"))); // NOI18N
        jLabel16.setText("Telefono:");

        txtTelefonoWinProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoWinProveedorActionPerformed(evt);
            }
        });

        btnGuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/success.png"))); // NOI18N
        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        btnCerrarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnCerrarProveedor.setText("Cerrar");
        btnCerrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout winAddProveedorLayout = new javax.swing.GroupLayout(winAddProveedor.getContentPane());
        winAddProveedor.getContentPane().setLayout(winAddProveedorLayout);
        winAddProveedorLayout.setHorizontalGroup(
            winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(winAddProveedorLayout.createSequentialGroup()
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winAddProveedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(winAddProveedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))))
                .addGap(42, 42, 42)
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtRepresentanteWinProveedor)
                    .addComponent(txtCompaniaWinProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtIdWinProveedor)
                    .addComponent(txtTelefonoWinProveedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winAddProveedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarProveedor)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarProveedor)
                .addGap(79, 79, 79))
        );
        winAddProveedorLayout.setVerticalGroup(
            winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winAddProveedorLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdWinProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompaniaWinProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRepresentanteWinProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTelefonoWinProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(winAddProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor)
                    .addComponent(btnCerrarProveedor))
                .addGap(78, 78, 78))
        );

        mnEnviarDatos.setText("Enviar Datos");
        mnEnviarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEnviarDatosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnEnviarDatos);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblTotal.setText("jLabel1");

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducto.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblProducto);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Buscar por:");

        cmbSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Eliga Categoria)", "Nombre", "Categoria", "Proveedor", "Precio Unidad", " " }));
        cmbSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cleaning.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(cmbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnImprimir);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/return-on-investment.png"))); // NOI18N
        jButton6.setText("Cerrar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        winProducto.setTitle("Guardar");
        winProducto.setSize(470, 690);
        winProducto.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
                int fila = tblProducto.getSelectedRow();
                if(fila != -1){
                        String id = tblProducto.getValueAt(fila, 0).toString();
                        int resp = JOptionPane.showConfirmDialog(rootPane, "esta seguro eliminar a "+ id, "Eliminar", JOptionPane.YES_OPTION);
                        if (resp == JOptionPane.YES_OPTION){
                                if (productosDao.eliminarProducto(id)){
                                        JOptionPane.showMessageDialog(rootPane, "eliminado");
                                        cargarDatosProducto();
                                    }else {
                                        JOptionPane.showMessageDialog(rootPane, "problemas...");
                                    }
                            }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Seleccione el registro a eliminar",
                                "Eliminar",
                                JOptionPane.ERROR_MESSAGE);
                    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
                int fila = tblProducto.getSelectedRow();
                if (fila != -1) {
                        winProducto.setSize(470, 690);
                        winProducto.setTitle("Editar");
                        winProducto.setVisible(true);
                        String id = tblProducto.getValueAt(fila, 0).toString();
                        Producto producto= productosDao.buscarProducto(id);
                        txtProducto.setText(producto.getIdProducto());
                        txtNombre.setText(producto.getNombreProducto());
                        txtPrecio.setText(Double.toString(producto.getPrecioUnidad()));
                        txtUnidades.setText(Integer.toString(producto.getUnidadExistecia()));
                        cmbCategoria.setSelectedItem(producto.getIdCategoria());
                        cmbProveedor.setSelectedItem(producto.getIdProveedor());
                      } else {
                        JOptionPane.showMessageDialog(rootPane, "Elija el Producto a Editar", "Editar", JOptionPane.ERROR_MESSAGE);
                    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            tblProducto.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
         String msgError = ValidarDatos();
        if (msgError.equals("")) {
            Producto producto = new Producto();
            producto.setIdProducto(txtProducto.getText());
            producto.setNombreProducto(txtNombre.getText());
            producto.setPrecioUnidad(Double.parseDouble(txtPrecio.getText()));
            producto.setUnidadExistecia(Integer.parseInt(txtUnidades.getText()));
            producto.setIdCategoria(cmbCategoria.getSelectedItem().toString());
            producto.setIdProveedor(cmbProveedor.getSelectedItem().toString());
             if (winProducto.getTitle().equals("Guardar")) {
                if (productosDao.buscarProducto(producto.getIdProducto()) == null) {
                    if (productosDao.guardarProducto(producto)) {
                        cargarDatosProducto();
                        JOptionPane.showMessageDialog(winProducto,
                            "Producto guardado exitosamente", "Guardar",
                            JOptionPane.INFORMATION_MESSAGE);
                        winProducto.dispose();
                    } else {
                        JOptionPane.showMessageDialog(winProducto,
                            "Error al intentar guardar", "Guardar",
                            JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(winProducto, "Identificacion ya registrada",
                        "Guardar", JOptionPane.ERROR_MESSAGE);
                }
            } else {//Desea editar
                if (productosDao.editarProducto(producto)) {
                    cargarDatosProducto();
                    JOptionPane.showMessageDialog(winProducto,
                        "Producto editado exitosamente", "Editar",
                        JOptionPane.INFORMATION_MESSAGE);
                    winProducto.dispose();
                } else {
                    JOptionPane.showMessageDialog(winProducto,
                        "Error al intentar editar", "Editar",
                        JOptionPane.ERROR_MESSAGE);
                }
            }

        } else {
            JOptionPane.showMessageDialog(winProducto, msgError, "Guardar",
                JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     winProducto.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCategoriaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaIdActionPerformed

    private void btnAddProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProveedorActionPerformed
        winAddProveedor.setSize(440, 520);
        winAddProveedor.setVisible(true);
        winAddProveedor.setTitle("Guardar un Proveedor");
        LimpiarCamposWinProveedor();
    }//GEN-LAST:event_btnAddProveedorActionPerformed

    private void btnAddCategoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoActionPerformed
        winAddCategoria.setSize(470, 600);
        winAddCategoria.setTitle("Guardar");
        winAddCategoria.setVisible(true);
        
        LimpiarCamposWinCatego();
    }//GEN-LAST:event_btnAddCategoActionPerformed

    private void btnSaveCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCategoriaActionPerformed
            String msgError = ValidarDatosWinCategoria();
            if (msgError.equals("")) {
            Categoria cats = new Categoria();
            cats.setIdCategoria(txtCategoriaId.getText());
            cats.setNombreCategoria(txtNombreCategoria.getText());
            cats.setDescripcion(txtNombreDesc.getText());

            if (winAddCategoria.getTitle().equals("Guardar")) {
                if (categoriaDao.buscarCategoria(cats.getIdCategoria()) == null) {
                    if (categoriaDao.GuardarCategoria(cats)) {
                        cargarCategoria();
                        JOptionPane.showMessageDialog(winAddCategoria,
                                "Categoria guardado exitosamente", "Guardar",
                                JOptionPane.INFORMATION_MESSAGE);
                        winAddCategoria.dispose();
                    } else {
                        JOptionPane.showMessageDialog(winAddCategoria,
                                "Error al intentar guardar", "Guardar",
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(winAddCategoria, "Identificacion ya registrada",
                            "Guardar", JOptionPane.ERROR_MESSAGE);
                }
            } else {//Desea editar // no estoy seguro si nesecita esa parte el boton pero yo la pongo por si acaso 
                if (categoriaDao.editarCategoria(cats)) {
                    cargarCategoria();
                    JOptionPane.showMessageDialog(winAddCategoria,
                            "Proveedor editado exitosamente", "Editar",
                            JOptionPane.INFORMATION_MESSAGE);
                    winAddCategoria.dispose();
                } else {
                    JOptionPane.showMessageDialog(winAddCategoria,
                            "Error al intentar editar", "Editar",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
                
                
        } else {
            JOptionPane.showMessageDialog(winAddCategoria, msgError, "Guardar",
                    JOptionPane.ERROR_MESSAGE);
       
        }
    }//GEN-LAST:event_btnSaveCategoriaActionPerformed

    private void btnAtrasCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCategoriaActionPerformed
        winAddCategoria.dispose();
    }//GEN-LAST:event_btnAtrasCategoriaActionPerformed

    private void txtIdWinProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdWinProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdWinProveedorActionPerformed

    private void txtCompaniaWinProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompaniaWinProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompaniaWinProveedorActionPerformed

    private void txtRepresentanteWinProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepresentanteWinProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepresentanteWinProveedorActionPerformed

    private void txtTelefonoWinProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoWinProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoWinProveedorActionPerformed

    private void btnCerrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarProveedorActionPerformed
       winAddProveedor.dispose();
    }//GEN-LAST:event_btnCerrarProveedorActionPerformed

    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
              String msgError = ValidarDatosProveedor();
        if (msgError.equals("")) {
            Proveedor proveedors = new Proveedor();
            proveedors.setId(txtIdWinProveedor.getText());
            proveedors.setNombre(txtRepresentanteWinProveedor.getText());
            proveedors.setTelefono(txtTelefonoWinProveedor.getText());
            proveedors.setCompania(txtCompaniaWinProveedor.getText());
  
            if (winAddProveedor.getTitle().equals("Guardar")) {
                if (proveedoresDao.buscarProveedor(proveedors.getId()) == null) {
                    if (proveedoresDao.guardarProveedor(proveedors)) {
                        cargarDatosProveedor();
                        JOptionPane.showMessageDialog(winAddProveedor,
                            "Proveedor guardado exitosamente", "Guardar",
                            JOptionPane.INFORMATION_MESSAGE);
                        winAddProveedor.dispose();
                    } else {
                        JOptionPane.showMessageDialog(winAddProveedor,
                            "Error al intentar guardar", "Guardar",
                            JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(winAddProveedor, "Identificacion ya registrada",
                        "Guardar", JOptionPane.ERROR_MESSAGE);
                }
            } else {//Desea editar
//                if (proveedoresDao.editarProveedor(proveedor)) {
//                    cargarDatosProveedor();
//                    JOptionPane.showMessageDialog(winAddProveedor,
//                        "Proveedor editado exitosamente", "Editar",
//                        JOptionPane.INFORMATION_MESSAGE);
//                    winAddProveedor.dispose();
//                } else {
//                    JOptionPane.showMessageDialog(winAddProveedor,
//                        "Error al intentar editar", "Editar",
//                        JOptionPane.ERROR_MESSAGE);
//                }
//            }
//
//        } else {
            JOptionPane.showMessageDialog(winAddProveedor, msgError, "Guardar",
                JOptionPane.ERROR_MESSAGE);
            }
            }
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (cmbSelect.getSelectedIndex() == 0) {
            cmbSelect.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Debe de selecionar una categoria",
                "Consulta", JOptionPane.ERROR_MESSAGE);
        }else if (txtDatos.getText().equals("")){
            txtDatos.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar consulta",
                "Consulta", JOptionPane.ERROR_MESSAGE);
        }else{
            FiltrarDatos();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtDatos.setText("");
        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{},
            new String[]{
                "IDPRODUCTO", "NOMBREPRODUCTO", "PRECIOUNIDAD", "UNIDADEXISTENTE","IDPROVEEDOR", "IDCATEGORIA"
            }));
             cargarDatosProducto();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProveedorActionPerformed

    private void mnEnviarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEnviarDatosActionPerformed
        // TODO add your handling code here:
                int fila = tblProducto.getSelectedRow();
        try {
            if(fila==-1)
            {
                JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");

            }
            else
            {
               String id = tblProducto.getValueAt(fila, 0).toString();
            Producto producto = productosDao.buscarProducto(id);
            frmFacturacion.txtIdProducto.setText(producto.getIdProducto());
            frmFacturacion.txtProducto.setText(producto.getNombreProducto());
            frmFacturacion.txtCantidad.setText(Integer.toString(producto.getUnidadExistecia()));
//            this.dispose();
            
            String cantidad = JOptionPane.showInputDialog("ingrese cantidad");
            if(cantidad.equals("") || cantidad.equals("0") ){
                JOptionPane.showMessageDialog(rootPane, "Debe de ingrese una cantidad");
            }else{
                //convierte el parametro string que ingreso en showInputDialogo a int
                int cantConver =Integer.parseInt(cantidad);
              //aqui como que hiria la restricion del inventario
            }
            

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mnEnviarDatosActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAddCatego;
    private javax.swing.JButton btnAddProveedor;
    private javax.swing.JButton btnAtrasCategoria;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarProveedor;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSaveCategoria;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JComboBox<String> cmbSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuItem mnEnviarDatos;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txtCategoriaId;
    private javax.swing.JTextField txtCompaniaWinProveedor;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtIdWinProveedor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCategoria;
    private javax.swing.JTextArea txtNombreDesc;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtRepresentanteWinProveedor;
    private javax.swing.JTextField txtTelefonoWinProveedor;
    private javax.swing.JTextField txtUnidades;
    private javax.swing.JDialog winAddCategoria;
    private javax.swing.JDialog winAddProveedor;
    private javax.swing.JDialog winProducto;
    // End of variables declaration//GEN-END:variables
       public void LimpiarCamposWinProveedor(){
        
      
        txtIdWinProveedor.setText(""); 
        txtRepresentanteWinProveedor.setText("");
        txtTelefonoWinProveedor.setText("");
        txtCompaniaWinProveedor.setText("");
        
        
        
    }
    
    private void cargarDatosProveedor() {
        proveedoresDao.conectarBD();
        ResultSet rs = proveedoresDao.cargarProveedor();
        if (rs !=null){
            System.out.println("Datos de proveedor cargados con exito");
        tblProducto.setModel(productosDao.cargarEnTabla(rs));
        lblTotal.setText("TOTAL: "+ tblProducto.getRowCount());
        }
        proveedoresDao.desconectarBD();
    }
    
    
    private String ValidarDatosProveedor(){
       if (txtIdWinProveedor.getText().trim().equals("")){
    txtIdWinProveedor.requestFocus();
    return "Identificacion es requerida";
    }
    if (txtRepresentanteWinProveedor.getText().trim().equals("")){
    txtRepresentanteWinProveedor.requestFocus();
    return "El nombre del Representante es requerido";
    }
    if (txtTelefonoWinProveedor.getText().trim().equals("")){
    txtTelefonoWinProveedor.requestFocus();
    return "El telefono es requerido";
    }else{
        try{
        Integer.parseInt(txtTelefonoWinProveedor.getText());
        }catch(NumberFormatException e){
        return "El telefono solo admite numeros.";
        }
    }
    if (txtCompaniaWinProveedor.getText().trim().equals("")){
    txtCompaniaWinProveedor.requestFocus();
    return "La compañia es requerido";}
     return ""; 
    }
    
    
    
    
    private String ValidarDatosWinCategoria() {
        if (txtCategoriaId.getText().trim().equals("")) {
            txtCategoriaId.requestFocus();
            return "Ingrese un numero";
        }
        if (txtNombreCategoria.getText().trim().equals("")) {
            txtNombreCategoria.requestFocus();
            return "La categoria es requerida";
        }
        if (txtNombreDesc.getText().trim().equals("")) {
            txtNombreDesc.requestFocus();
            return "Ingrese una descripcion del producto";
        }
        return "";
    }
    
    
    private void cargarCategoria() {

        categoriaDao.conectarBD();
        ResultSet rs = categoriaDao.cargarDatosCategoria();
        if (rs != null) {
            System.out.println("Datos cargados");
            //tblProductos.setModel(CategoriaDao.cargarEnTabla(rs));
            //lbltotal.setText("TOTAL: " + tblProductos.getRowCount());
        }
        categoriaDao.desconectarBD();

    }
    public void LimpiarCamposWinCatego(){
        
      
        txtCategoriaId.setText(""); 
        txtNombreCategoria.setText("");
        txtNombreDesc.setText("");
        
        
        
    }
 public void limpiarCampos(){
        
        //Limpia los campos necesarios
        txtProducto.setText(""); 
        txtNombre.setText("");
        txtPrecio.setText("");
        txtUnidades.setText("");
        cmbCategoria.setSelectedIndex(0);
        cmbProveedor.setSelectedIndex(0);
    }
    
    private String ValidarDatos(){
        
        if(txtProducto.getText().trim().equals("")){
            txtProducto.requestFocus();
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar un producto");
        }
        if(txtNombre.getText().trim().equals("")){
            txtNombre.requestFocus();
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar un el nombre del producto");
        }
        if(txtPrecio.getText().trim().equals("")){
            txtPrecio.requestFocus();
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar el precio");
        }else{
            try{
             Double.parseDouble(txtPrecio.getText());
                
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane,"Solo se permiten numeros");
            }
        }
        if(txtUnidades.getText().trim().equals("")){
            txtUnidades.requestFocus();
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar la cantidad de unidades");
        }else{
            try {
                Integer.parseInt(txtUnidades.getText());

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane,"Debe ingresar un producto");
            }
        }if(cmbProveedor.getSelectedIndex()==0){
            cmbProveedor.requestFocus();
            cmbProveedor.showPopup();
            JOptionPane.showMessageDialog(rootPane,"Debe seleccionar un proveedor");
        }
        if(cmbCategoria.getSelectedIndex()==0){
            cmbCategoria.requestFocus();
            cmbCategoria.showPopup(); // Desglega la lista del combobox 
            JOptionPane.showMessageDialog(rootPane,"Debe seleccionar una categoria");
        }
        
        return "";
    }
    private void cargarDatosProducto() {
       productosDao.conectarBD();
       ResultSet rs = productosDao.cargarProducto();
       if(rs !=null){
           tblProducto.setModel(productosDao.cargarEnTabla(rs));
           lblTotal.setText("TOTAL: "+tblProducto.getRowCount());
           
       }
        productosDao.desconectarBD();
    }
    public void FiltrarDatos() {
        Conexion conexion = new Conexion();
        String sql;
        ResultSet rs;
        conexion.conectarBD();
        switch (cmbSelect.getSelectedItem().toString()) {
            case "Nombre":
                sql = "SELECT * FROM producto WHERE Nombre LIKE '%" + txtDatos.getText() + "%'";
                break;
            case "Categoria":
                sql = "SELECT * FROM producto WHERE Idcategoria LIKE '%" + txtDatos.getText() + "%'";
                break;
            case "Proveedor":
                sql = "SELECT * FROM producto WHERE IdProveedor LIKE '%" + txtDatos.getText() + "%'";
                break;
            case "Precio Unidad":
                sql = "SELECT * FROM producto WHERE Precio LIKE '%" + txtDatos.getText() + "%'";
                break;
            default:
                sql = " ";
                break;
        }
        if (sql.contains("SELECT")) {
            rs = conexion.seleccionar(sql);
            if (rs != null) {
                tblProducto.setModel(conexion.cargarEnTabla(rs));
                lblTotal.setText("TOTAL: " + tblProducto.getRowCount());
            }
        }
        conexion.desconectarBD();
    }
}
